name: Format and Linter Checks
on:
  - workflow_dispatch
  - push
  - pull_request
permissions:
  id-token: write
  contents: read
jobs:
  checks:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Python linting # ref: https://github.com/astral-sh/ruff
        if: always()
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.7.1
          args: check --no-cache --exclude "*.ipynb"
          src: ./src/api

      - name: Python formatting
        if: always()
        uses: astral-sh/ruff-action@v3
        with:
          version: 0.7.1
          args: format --check --exclude "*.ipynb"
          src: ./src/api

      - name: Validate YAML file
        if: always()
        run: yamllint ./src/api --config-file .yamllint.yaml

      - name: Python import sorts
        if: always()
        uses: isort/isort-action@v1.1.1
        with:
          isort-version: 5.13.2
          configuration: --profile black --check-only --diff
          sort-paths: ./src/api

      - name: Docker linter # ref: https://github.com/marketplace/actions/hadolint-action
        if: always()
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: |
            src/api/Dockerfile
